spring.application.name=tpcm_spring
spring.application.version=1
server.port=8080

app.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
app.datasource.username=tpcm_app
app.datasource.password=tpcm_pass
app.datasource.driver-class-name=oracle.jdbc.OracleDriver

clients.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
clients.datasource.username=tpcm_db
clients.datasource.password=tpcm_pass
clients.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.kafka.bootstrap-servers=localhost:9092

kafka.topics.customer-updates=customer-updates
kafka.topics.subscriber-updates=subscriber-updates
kafka.topics.user-updates=user-updates

spring.main.banner-mode=off

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.session.store-type=none