spring.application.name=tpcm-scheduler
spring.application.version=1.0
server.port=7000

app.datasource.url=jdbc:oracle:thin:@//oracle:1521/FREEPDB1
app.datasource.username=tpcm_app
app.datasource.password=tpcm_pass

clients.datasource.url=jdbc:oracle:thin:@//oracle:1521/FREEPDB1
clients.datasource.username=tpcm_db
clients.datasource.password=tpcm_pass

management.endpoints.web.exposure.include=*
#http://localhost:7000/actuator/scheduledtasks
management.endpoint.health.show-details=always
spring.session.store-type=none

spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=tpcm-scheduler-

spring.main.banner-mode=off