spring.application.name=tpcm-scheduler
spring.application.version=1.0
server.port=7000

app.datasource.url=jdbc:oracle:thin:@//oracle-tpcm:1521/freepdb1
app.datasource.username=tpcm_app
app.datasource.password=tpcm_pass

clients.datasource.url=jdbc:oracle:thin:@//oracle-tpcm:1521/freepdb1
clients.datasource.username=tpcm_db
clients.datasource.password=tpcm_pass

spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=tpcm-scheduler-

spring.main.banner-mode=off

schedule.cron.reset-threshold=0 0 0 * * *
schedule.cron.delete-old-transactions=0 0 20 * * *
schedule.cron.delete-uncommitted-transactions=0 0 22 * * *
schedule.cron.delete-old-subscriber-logs=0 0 3 * * FRI
schedule.cron.delete-old-customer-logs=0 0 3 * * SAT
schedule.cron.delete-old-app-events=0 0 3 * * SUN
schedule.cron.partition-transactions=0 0 23 L * *