spring.application.name=tpcm-scheduler
spring.application.version=1.0
server.port=7000

app.datasource.url=jdbc:oracle:thin:@//oracle-tpcm:1521/XE
app.datasource.username=tpcm_app
app.datasource.password=tpcm_pass

clients.datasource.url=jdbc:oracle:thin:@//oracle-tpcm:1521/XE
clients.datasource.username=tpcm_db
clients.datasource.password=tpcm_pass

spring.task.scheduling.pool.size=5
spring.task.scheduling.thread-name-prefix=tpcm-scheduler-

spring.main.banner-mode=off