CREATE TABLE SubscriberAuth (
    authID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subscriberID     NUMBER NOT NULL,
    authProvider     VARCHAR2(20) NOT NULL,
    providerUserID   VARCHAR2(255) NOT NULL,
    email            VARCHAR2(255),
    displayName      VARCHAR2(255),
    createdAt        TIMESTAMP DEFAULT SYSTIMESTAMP,
    lastLogin        TIMESTAMP,
    
    CONSTRAINT fk_subauth_subscriber FOREIGN KEY (subscriberID) REFERENCES Subscriber(subscriberID),
    CONSTRAINT uq_provider_user UNIQUE (authProvider, providerUserID)
);

ALTER TABLE SubscriberAuth ADD (
    userRole VARCHAR2(20) DEFAULT 'USER'
);