--------------------- Customer Table ---------------------
CREATE TABLE Customer (
    customerID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name             VARCHAR2(255),
    type             VARCHAR2(50),
    nrSubscribers    INTEGER,
    billCycleDay     NUMBER(2)
)
-- create a partition for every bill day
PARTITION BY LIST (billCycleDay) (
    PARTITION p_1 VALUES (1),
    PARTITION p_2 VALUES (2),
    PARTITION p_3 VALUES (3),
    PARTITION p_4 VALUES (4),
    PARTITION p_5 VALUES (5),
    PARTITION p_6 VALUES (6),
    PARTITION p_7 VALUES (7),
    PARTITION p_8 VALUES (8),
    PARTITION p_9 VALUES (9),
    PARTITION p_10 VALUES (10),
    PARTITION p_11 VALUES (11),
    PARTITION p_12 VALUES (12),
    PARTITION p_13 VALUES (13),
    PARTITION p_14 VALUES (14),
    PARTITION p_15 VALUES (15),
    PARTITION p_16 VALUES (16),
    PARTITION p_17 VALUES (17),
    PARTITION p_18 VALUES (18),
    PARTITION p_19 VALUES (19),
    PARTITION p_20 VALUES (20),
    PARTITION p_21 VALUES (21),
    PARTITION p_22 VALUES (22),
    PARTITION p_23 VALUES (23),
    PARTITION p_24 VALUES (24),
    PARTITION p_25 VALUES (25),
    PARTITION p_26 VALUES (26),
    PARTITION p_27 VALUES (27),
    PARTITION p_28 VALUES (28),
    PARTITION p_29 VALUES (29),
    PARTITION p_30 VALUES (30),
    PARTITION p_31 VALUES (31),
    PARTITION p_default VALUES (NULL)
);

-- Shortcut to drop all tables
DROP TABLE  AppUser PURGE;
DROP TABLE Subscriber PURGE;
DROP TABLE Customer PURGE;
DROP TABLE Limit PURGE;
DROP TABLE ThirdParty PURGE;
DROP TABLE Transaction PURGE;
DROP TABLE LogEvent PURGE;



--------------------- Subscriber Table ---------------------
CREATE TABLE Subscriber (
    subscriberID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MSISDN            VARCHAR2(20) UNIQUE NOT NULL,
    status            VARCHAR2(20),
    subscriptionType  VARCHAR2(20),
    customerID        NUMBER,
    CONSTRAINT fk_sub_customer FOREIGN KEY (customerID) REFERENCES Customer(customerID)
);

--------------------- Limit Table ---------------------
CREATE TABLE Limit (
    subscriberID         NUMBER PRIMARY KEY,
    consumedAmount       NUMBER DEFAULT 0,
    lastReset            TIMESTAMP DEFAULT SYSTIMESTAMP,
    maxAmountCycle       NUMBER DEFAULT 300,
    maxAmountTransaction NUMBER DEFAULT 50,
    CONSTRAINT fk_limit_subscriber FOREIGN KEY (subscriberID) REFERENCES Subscriber(subscriberID)
);

--------------------- ThirdParty Table ---------------------
CREATE TABLE ThirdParty (
    thirdPartyID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name           VARCHAR2(255),
    serviceType    VARCHAR2(100),
    email          VARCHAR2(255),
    active         CHAR(1) CHECK (active IN ('Y', 'N'))
);

--------------------- Transaction Table ---------------------
CREATE TABLE Transaction (
    transactionID   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subscriberID    NUMBER,
    createdDate     TIMESTAMP DEFAULT SYSTIMESTAMP,
    amount          NUMBER,
    channel         VARCHAR2(50),
    tpid            NUMBER,
    status          VARCHAR2(20),
    isCounted       CHAR(1) DEFAULT 'Y' CHECK (isCounted IN ('Y', 'N')),
    CONSTRAINT fk_transaction_subscriber FOREIGN KEY (subscriberID) REFERENCES Subscriber(subscriberID),
    CONSTRAINT fk_transaction_thirdparty FOREIGN KEY (tpid) REFERENCES ThirdParty(thirdPartyID)
)
PARTITION BY RANGE (createdDate) (
    PARTITION PART_2025_11 VALUES LESS THAN (TO_DATE('2024-12-01', 'YYYY-MM-DD'))
);

--------------------- AppUser Table ---------------------
CREATE TABLE AppUser (
    userID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(100) UNIQUE NOT NULL,
    passwordHash    VARCHAR2(255) NOT NULL,
    role            VARCHAR2(20),
    createdAt       TIMESTAMP DEFAULT SYSTIMESTAMP,
    lastLogin       TIMESTAMP
);

CREATE TABLE LogEvent (
    eventID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    eventType      VARCHAR2(50),
    transactionID  NUMBER,
    logTimeStamp   TIMESTAMP DEFAULT SYSTIMESTAMP,
    subscriberID   NUMBER,
    userID         NUMBER,
    detailedEvent  VARCHAR2(4000),
    CONSTRAINT fk_log_subscriber FOREIGN KEY (subscriberID) REFERENCES Subscriber(subscriberID),
    CONSTRAINT fk_log_user FOREIGN KEY (userID) REFERENCES AppUser(userID),
    CONSTRAINT fk_log_transaction FOREIGN KEY (transactionID) REFERENCES Transaction(transactionID)
)
PARTITION BY RANGE (logTimeStamp) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
    PARTITION PART_2025_11 VALUES LESS THAN (TO_DATE('2024-12-01', 'YYYY-MM-DD'))
);