--------------- Customer Table ---------------
CREATE TABLE Customer (
    customerID      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(255),
    type            VARCHAR2(20),
    nrSubscribers   INTEGER,
    billCycleDay    DATE,
    email           VARCHAR2(255),
    contactNumber   VARCHAR2(20),
    address         VARCHAR2(255)    
);
ALTER TABLE customer MODIFY (billCycleDay NUMBER(2));

--------------- Subscriber Table ---------------
CREATE TABLE Subscriber (
    subscriberID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    MSISDN              VARCHAR2(20),
    status              VARCHAR2(20),
    subscriptionType    VARCHAR2(20),
    customerID          NUMBER,
    CONSTRAINT fk_sub_customer FOREIGN KEY (customerID) REFERENCES Customer(customerID)
);

--------------- AppUser Table ---------------
CREATE TABLE AppUser (
    userID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username        VARCHAR2(100) UNIQUE NOT NULL,
    passwordHash    VARCHAR2(255) NOT NULL,
    role            VARCHAR2(20),
    createdAt       TIMESTAMP DEFAULT SYSTIMESTAMP,
    lastLogin       TIMESTAMP
);

--------------- CustomerLogs Table ---------------
CREATE TABLE CustomerLogs (
    logID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    customerID      NUMBER,
    operation       VARCHAR2(20),
    changedField    VARCHAR2(255),
    newValue        VARCHAR2(255),
    oldValue        VARCHAR2(255),
    timeOfChange    TIMESTAMP DEFAULT TRUNC(SYSDATE),
    userID          NUMBER,
    CONSTRAINT fk_log_customer FOREIGN KEY (customerID) REFERENCES Customer(customerID),
    CONSTRAINT fk_log_user FOREIGN KEY (userID) REFERENCES AppUser(userID)
)
PARTITION BY RANGE (timeOfChange) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
  PARTITION p_start VALUES LESS THAN (TO_DATE('2025-07-01', 'YYYY-MM-DD'))
);

-- maximum number of partitions displayed 2^20 = 1048576
select table_name,
       partitioning_type,
       partition_count
from user_part_tables
where table_name = 'CUSTOMERLOGS';

DROP TABLE IF EXISTS CustomerLogs PURGE;

-- here lists only 1 partition the one before 1st of July 2025
SELECT partition_name, high_value
FROM user_tab_partitions
WHERE table_name = 'CUSTOMERLOGS';

-------------- SubscriberLogs Table --------------
CREATE TABLE SubscriberLogs (
    logID           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    subscriberID    NUMBER,
    operation       VARCHAR2(20),
    changedField    VARCHAR2(255),
    newValue        VARCHAR2(255),
    oldValue        VARCHAR2(255),
    timeOfChange    TIMESTAMP DEFAULT TRUNC(SYSDATE),
    userID          NUMBER,
    CONSTRAINT fk_log_subscriber FOREIGN KEY (subscriberID) REFERENCES Subscriber(subscriberID),
    CONSTRAINT fk_log_sub_user FOREIGN KEY (userID) REFERENCES AppUser(userID)
)
PARTITION BY RANGE (timeOfChange) INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
(
  PARTITION p_start VALUES LESS THAN (TO_DATE('2025-07-01', 'YYYY-MM-DD'))
);

select table_name,
       partitioning_type,
       partition_count
from user_part_tables
where table_name = 'SUBSCRIBERLOGS';

select partition_name, high_value
from user_tab_partitions
where table_name = 'SUBSCRIBERLOGS';



