version: '3.8'

networks:
  tpcm-network:
    driver: bridge

volumes:
  oracle-data:

services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-tpcm
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=matcha123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - tpcm-network
    shm_size: 3g