networks:
  tpcm-network:
    driver: bridge

volumes:
  oracle-data:

services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-tpcm
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=matcha123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - tpcm-network
    shm_size: 3g
  tpcm-scheduler:
    build:
      context: ./tpcm-scheduler
      dockerfile: Dockerfile
    container_name: tpcm-scheduler
    ports:
      - "7000:7000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./tpcm-scheduler/logs:/app/logs
    depends_on:
      - oracle
    networks:
      - tpcm-network
    restart: unless-stopped