spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.listener.concurrency=3

tpcm.api.base-url=http://tpcm-spring:8080
tpcm.api.username=admin
tpcm.api.password=admin

tpcm.clients.base-url=http://tpcm-clients:8081
tpcm.clients.username=admin
tpcm.clients.password=admin
