spring.application.name=tpcm-kafka-consumer
spring.application.version=1.0
server.port=6999

tpcm.api.base-url=http://localhost:8080
tpcm.api.username=admin
tpcm.api.password=admin

tpcm.clients.base-url=http://localhost:8081
tpcm.clients.username=admin
tpcm.clients.password=admin

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=tpcm-consumer-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

logging.level.com.example.kafkaconsumer=INFO
logging.level.org.apache.kafka=WARN
spring.main.banner-mode=off

spring.main.allow-bean-definition-overriding=true