spring.application.name=tpcm_voice
server.port=4242

voice.datasource.url=jdbc:oracle:thin:@//oracle:1521/freepdb1
voice.datasource.username=tpcm_voice
voice.datasource.password=tpcm_pass
voice.datasource.driver-class-name=oracle.jdbc.OracleDriver

tpcm.api.url=http://tpcm-spring:8080
tpcm.api.username=admin
tpcm.api.password=admin