spring.application.name=tpcm-clients
spring.application.version=1
server.port=8081

clients.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
clients.datasource.username=tpcm_db
clients.datasource.password=tpcm_pass
clients.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.kafka.bootstrap-servers=localhost:9092

kafka.topics.customer-updates=customer-updates
kafka.topics.subscriber-updates=subscriber-updates
kafka.topics.user-updates=user-updates

jwt.secret=cheie-secreta-la-haladeala
jwt.expiration=3600000

spring.security.oauth2.client.registration.google.client-id=104390328408-gtnd1obton6fh9aeng1iq2e8h16s1g3n.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.main.banner-mode=off

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.session.store-type=none