spring.application.name=tpcm-clients
spring.application.version=1
server.port=8081

clients.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
clients.datasource.username=tpcm_db
clients.datasource.password=tpcm_pass
clients.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.kafka.bootstrap-servers=localhost:9092

kafka.topics.customer-updates=customer-updates
kafka.topics.subscriber-updates=subscriber-updates
kafka.topics.user-updates=user-updates

spring.main.banner-mode=off

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.session.store-type=none