spring.application.name=tpcm-clients
spring.application.version=1
server.port=8081

clients.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
clients.datasource.username=tpcm_db
clients.datasource.password=tpcm_pass
clients.datasource.driver-class-name=oracle.jdbc.OracleDriver

hikari.minimum-idle=3
hikari.maximum-pool-size=10
hikari.connection-test-query=SELECT 1 FROM DUAL

app.init.admin.username=admin
app.init.admin.password=admin
app.init.default-user.username=user
app.init.default-user.password=user
app.init.default-user.role=USER
app.init.default-admin.role=ADMIN

cors.allowed-origins=http://localhost:3000,http://127.0.0.1:3000

kafka.topics.customer-updates.partitions=3
kafka.topics.customer-updates.replication-factor=1
kafka.topics.subscriber-updates.partitions=3
kafka.topics.subscriber-updates.replication-factor=1
kafka.topics.user-updates.partitions=3
kafka.topics.user-updates.replication-factor=1

spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.bootstrap-servers=localhost:9092

kafka.topics.customer-updates=customer-updates
kafka.topics.subscriber-updates=subscriber-updates
kafka.topics.user-updates=user-updates

spring.main.banner-mode=off

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.session.store-type=none